# group_vars/all.yml

# The SSH key to add for Linux playbook
linux_ssh_key: "ssh-rsa DMHNFJMGHDHGSXCHVJGHCFDJXDCGHCV ssh_user"

# The SSH key to add for Windows playbook
linux_ssh_key: "ssh-rsa DMHNFJMGHDHGSXCHVJGHCFDJXDCGHCV ssh_user"
