---
- name: Add SSH key to all remote Linux machines
  hosts: all
  become: true
  gather_facts: true

  vars_prompt:
    - name: linux_ssh_key
      prompt: Enter the SSH key to add
      private: false
      default: "{{ linux_ssh_key | default('') }}"

  tasks:
    - name: Check if authorized_keys file exists for Linux hosts
      stat:
        path: "{{ linux_authorized_keys }}"
      register: file_status
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

    - name: Print a message if authorized_keys file does not exist for Linux hosts
      debug:
        msg: "The authorized_keys file does not exist"
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat" and not file_status.stat.exists

    - name: Ensure authorized_keys file exists for Linux hosts
      file:
        path: "{{ linux_authorized_keys }}"
        state: touch
        mode: 0600
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

    - name: Add SSH key to authorized_keys file for Linux hosts
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ linux_ssh_key }}"
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
